### ISSUE TITLE
请问项目是否使用了云账户的相关sdk?同步的时候一直在下载云账户的东西

### ISSUE THREAD

**Issue by Jeromeer** [leancloud/leancloud-demos#13]
如题,请问项目是否使用了云账户的相关sdk?同步的时候一直在下载云账户的东西,而且下载特别慢

**Comment by weakish** [comment]
时间过久，暂时先关掉了。如仍碰到类似问题，欢迎到 [LeanCloud论坛][0] 讨论。

[0]: https://forum.leancloud.cn/
