### ISSUE TITLE
Swift项目如何使用cocoapods来安装leancloud

### ISSUE THREAD

**Issue by pgbo** [leancloud/leancloud-demos#2]
我的项目是Swift，使用cocoapods来管理第三方库，项目里使用了leancloud的sdk，同时也使用了用纯swift的HanekeSwift，因此我在Podfile中用use_frameworks!来标明pod为我安装依赖库时使用framework方式（具体可参考：http://blog.cocoapods.org/CocoaPods-0.36/）。 在这种情况下，使用pod install出来的都是framework（.framework文件），我的项目能够通过编译，但在运行时在调用leancloud的代码处就出错，具体如下：
![image](https://cloud.githubusercontent.com/assets/4122686/8539926/74c18300-24b3-11e5-953d-e05aadcbce27.png)

  然后我把Podfile中的和swift库的相关配置语句和use_frameworks!删除，这时候pod install出来的是静态库（.a文件），并且这时候编译和运行我的程序也是是OK的。

我的项目情况：
1.Swift项目
2.使用cocoapods管理第三方库
3.使用leancloud，在pod install后通过Objective-c bridging header来使用leancloud sdk
4.同时使用像HanekeSwift这样的纯Swift第三方库（不得不使用use_frameworks!来使cocoapods支持安装它）

问题：
这时候使用leancloud就会出现运行时错误。

 再次查看http://blog.cocoapods.org/CocoaPods-0.36 这篇文章，里面有一个一段讲述cocoapods是如何支持Swift项目的：
![image](https://cloud.githubusercontent.com/assets/4122686/8540000/166764e0-24b4-11e5-9e6b-c9ed28975b4c.png)

所以leancloud有什么好的方法解决我这个问题？不要告诉我手动添加到项目里！

**Comment by lzwjava** [comment]
试试最新的库？
```
pod 'AVOSCloud', '3.1.2.8'
```

现在解决了吗？

**Comment by lzwjava** [comment]
@pgbo 可以参考下这个项目，是用 swift + pod 构建的。https://github.com/pgbo/WukongSNS

**Comment by lzwjava** [comment]
好吧，就是你的库，我错了。。
