### ISSUE TITLE
When I run the sample in AndroidStudio I got an error!

### ISSUE THREAD

**Issue by ForgetV** [leancloud/leancloud-demos#4]
Error:Execution failed for task ':app:packageDebug'.
> Duplicate files copied in APK META-INF/LICENSE.txt
  	File 1: /Users/demon/Desktop/PushAndTalk/libs/fastjson.jar
  	File 2: /Users/demon/Desktop/PushAndTalk/libs/httpmime-4.2.4.jar

**Comment by at15** [comment]
add  the following in your `build.gradle` should fix this problem
````
packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }
````
btw: the log points out this solution after logging the error.

**Comment by ForgetV** [comment]
Error:(25, 0) Gradle DSL method not found: 'packagingOptions()'
Possible causes:The project 'PushAndTalk' may be using a version of Gradle that does not contain the method.

**Comment by ForgetV** [comment]
I download the demon from:https://github.com/leancloud/LeanMessage-Demo and import it into my text project,but when i sync project i get ButterKnife use incorrect error.after i fix that i get this one.

**Comment by at15** [comment]
which `build.gradle` are you using? should be the one inside `app` folder, see https://github.com/leancloud/android-push-demo/blob/master/app/build.gradle

**Comment by ForgetV** [comment]
inside app folder

**Comment by ForgetV** [comment]
pply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "android.alex.com.pushandtalk"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
repositories {
    maven { url "https://jitpack.io" }
}

packagingOptions{
    exclude 'META-INF/LICENSE.txt'
    exclude 'META-INF/NOTICE.txt'
}
lintOptions {
    abortOnError false
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.android.support:recyclerview-v7:23.0.1'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'de.greenrobot:eventbus:2.4.0'
    compile 'com.github.stuxuhai:jpinyin:3e391ae0a7'
    compile files('/Users/demon/Desktop/PushAndTalk/libs/avoscloud-push-v3.9.jar')
    compile files('/Users/demon/Desktop/PushAndTalk/libs/avoscloud-sdk-v3.9.jar')
    compile files('/Users/demon/Desktop/PushAndTalk/libs/avoscloud-statistics-v3.9.jar')
    compile files('/Users/demon/Desktop/PushAndTalk/libs/fastjson.jar')
    compile files('/Users/demon/Desktop/PushAndTalk/libs/httpmime-4.2.4.jar')
    compile files('/Users/demon/Desktop/PushAndTalk/libs/Java-WebSocket-1.2.0-leancloud.jar')
    compile files('/Users/demon/Desktop/PushAndTalk/libs/okhttp-2.5.0.jar')
}

**Comment by ForgetV** [comment]
Thanks，
I should move packagingOptions into the android closure,

**Comment by at15** [comment]
@ForgetV you are welcome, and don't forget to close the issue. :)
